spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: P@ssw0rd
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
